### ISSUE TITLE
Firewall rule missing for RabbitMQ

### ISSUE THREAD

**Issue by clarkadamp** [puppetlabs-toy-chest/puppetlabs-havana#18]
Hi,
  I am attempting to use the puppetlabs-havana module and the puppet run fails on the controller node build when trying to run /sbin/service rabbitmq-server start

Error: Could not start Service[rabbitmq-server]: Execution of '/sbin/service rabbitmq-server start' returned 1: 
Error: /Stage[main]/Rabbitmq::Service/Service[rabbitmq-server]/ensure: change from stopped to running failed: Could not start Service[rabbitmq-server]: Execution of '/sbin/service rabbitmq-server start' returned 1: 

If I run that command manually, I get the same error.  As expected.
If I "service iptables stop" I can run the command successfully.

On the next puppet run, it got further, but errored like below:
Error: /Stage[main]/Nova::Rabbitmq/Rabbitmq_user_permissions[openstack@/]: Could not evaluate: Execution of '/usr/sbin/rabbitmqctl list_user_permissions openstack' returned 2: Listing permissions for user "openstack" ...
Error: unable to connect to node 'rabbit@controller-1': nodedown
# DIAGNOSTICS

nodes in question: ['rabbit@controller-1']

hosts, their running nodes and ports:
- unable to connect to epmd on controller-1: address (cannot connect to host/port)

current node details:
- node name: 'rabbitmqctl21552@controller-1'
- home dir: /var/lib/rabbitmq
- cookie hash: jeksUQHfkCxLqaPwlesT0Q==

Again if I stop iptables and run it manually it runs successfully.

Adam

**Comment by clarkadamp** [comment]
I have found the culprit, rabbitmq binds to various ports:
[root@controller-1 ~]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name  
tcp        0      0 0.0.0.0:4369                0.0.0.0:\*                   LISTEN      12660/epmd  
tcp        0      0 0.0.0.0:48835               0.0.0.0:\*                   LISTEN      12720/beam  
tcp        0      0 :::5672                     :::\*                        LISTEN      12720/beam   

epmd and beam on 5672 are always there so that should be easy to solve.  The other one, beam on 48835 seems to be ephemeral.  It can be locked down in /usr/lib/rabbitmq/bin/rabbitmq-env, for example:
SERVER_ERL_ARGS="+K true +A30 +P 1048576 \
  -kernel inet_default_connect_options [{nodelay,true}] \
  -kernel inet_dist_listen_min 35197 \
  -kernel inet_dist_listen_max 35198"

in which those are the ports it will choose from, set the min/max the same and it will be only on that port.  

Given that havana::profile::rabbitmq is a wrapper for nova::rabbitmq which is a wrapper for rabbitmq::service, which is where the template for /usr/lib/rabbitmq/bin/rabbitmq-env probably should exist and the firewalls resources are scattered throughout the other modules what is the best way to tackle this?

**Comment by hogepodge** [comment]
My approach is to use an internal network that allows all connections, and to send Rabbit traffic over that. Currently rule 9998 in the firewall.

**Comment by clarkadamp** [comment]
It could also be that the way that I have my routing setup for with the default routes and dhcp, hostnames are resolving to the API network instead of the management network.  Damnit.

**Comment by clarkadamp** [comment]
@hogepodge; yup, just verified with tcpdump on that.

How is rabbit/epmd deciding which hostname/ip is used?

**Comment by hogepodge** [comment]
By default Rabbit is going to start up listening on all ports. My approach to the firewall is to have all services listen everywhere, then shut down all of the ports except where I want traffic to happen. Reading from the bottom of the iptables you'll see that the last evaluated rule rejects all traffic. The rule before it accepts all traffic on the management network. I try to direct all internal traffic on the management network, with the assumption that it is not accessible to the external world. The rest of the rules are concerned with opening up ports on the external API network. For the design of this deployment it's critical that the internal and external networks be different for that reason.

**Comment by clarkadamp** [comment]
Yep, spot on

**Comment by hogepodge** [comment]
I also wanted to comment about RabbitMQ. It can be very picky about how it tries to connect. If you're running into troubles, I suggest updating the hosts file so that the hostname resolves to 127.0.0.1. I ran into problems when I didn't have that set up.

**Comment by philbert** [comment]
Thanks! Hit this same problem with puppetlabs-openstack icehouse. Pointing the hostname to 127.0.0.1 fixed it.

**Comment by wenchma** [comment]
Thanks! I am running into this problem, mapping the hostname to 127.0.0.1 fixed it.

**Comment by sakibsys** [comment]
Worked for me. Thanks.
