### ISSUE TITLE
Neutron: Can't reach metadata/gateway or Internet connective inside my VM using 2NICs

### ISSUE THREAD

**Issue by guimaluf** [puppetlabs-toy-chest/puppetlabs-havana#30]
I've set up my network using two NICs as follow

```
auto br-ex eth0 eth1 lo

allow-hotplug br-ex eth0 eth1

iface br-ex inet dhcp

iface eth0 inet static
address 0.0.0.0
down ip l s $IFACE down
up ip l s $IFACE up

iface eth1 inet static
address 10.0.0.102
netmask 255.255.255.0
```

And my hiera

```
######## Networks
havana::network::api: '200.232.7.0/24'
havana::network::external: '200.232.7.0/24'
havana::network::management: '10.0.0.0/24'
havana::network::data: '10.0.0.0/24'

######## Fixed IPs (controllers)

havana::controller::address::api: '200.232.7.102'
havana::controller::address::management: '10.0.0.102'
havana::storage::address::api: '200.232.7.102'
havana::storage::address::management: '10.0.0.102'
```

I've created my ext network with options

``` +---------------------------+--------------------------------------+
| Field                     | Value                                |
+---------------------------+--------------------------------------+
| admin_state_up            | True                                 |
| id                        | 31c76aec-0a1f-46d9-989d-c5a3b97d0ef0 |
| name                      | external                             |
| provider:network_type     | gre                                  |
| provider:physical_network |                                      |
| provider:segmentation_id  | 1                                    |
| router:external           | True                                 |
| shared                    | True                                 |
| status                    | ACTIVE                               |
| subnets                   | b69d91e5-e86c-4956-8229-09c5d6e68a07 |
| tenant_id                 | 6ca99f9d5f8b4a2aa17967a7e8e6915a     |
+---------------------------+--------------------------------------+
```

My VM can get IP and I can ping metadata/gateway IP with
`ip netns exec qdhcp-31c76aec-0a1f-46d9-989d-c5a3b97d0ef0`

But inside my VM nothings happens.
I'm trying to see if is firewall related issue.

**Comment by guimaluf** [comment]
Look's Cirros image can't get static routes, so isn't setting metadata route to metadata server.
Ubuntu UEC can get net IP, reach metadata server, but I still can't reach the VM outside network. Probably is lack of neutron knowledge

**Comment by hogepodge** [comment]
Neutron is fairly tricky to work with. I have this situation with my setup:

192.168.22.0/24 is my external network. In my test environment, by gateway and name server is 192.168.22.2. These may be different in your environments, but they're both important to have available. For the public network I turn dhcp off and set the gateway and name server to 192.168.22.2. I also assign an IP range that excludes any special services on my external network. A safe example (and not necessarily relevant to your environment) is start=192.168.22.100,end=192.168.22.200.

I set up a private network, say 10.0.0.0/24. I attach it to the public network with a router that has the public network set as the external gateway. I also set the dns option on the private network to be 192.168.22.2. Although this assumes that the public network is connected, it's the only way to resolve names. When you assign a floating ip to your publicly addressed machine all of the routing should happen properly.

Of course, this assumes that your routing from the public network to the neutron node is proper, which is a bit outside the scope of the module.

Right now I'm working on a patch that will allow you to automatically set up the public network, a private network, and the router between them. It's going to require some changes to the puppet-neutron providers which are in review right now. My hope is that this will add another layer of abstraction that takes away the tedium of correctly setting up a neutron network.

**Comment by guimaluf** [comment]
I think would be nice to have a working net config example in README, so neutron could work like a charm.
Something like `/etc/sysconfig/netconfig` or `/etc/network/interface` files

**Comment by hogepodge** [comment]
There's an update upstream for neutron that's going to allow us to set up networking automatically within the manifest. It's being code reviewed right now, and as soon as it lands that the code here can be used https://github.com/puppetlabs/puppetlabs-havana/blob/master/manifests/setup/sharednetwork.pp (right now it will break without the neutron patch).

**Comment by hogepodge** [comment]
What does your deployment scenario look like? Bare metal? Virtual machines? If VMs, which hypervisor?

**Comment by guimaluf** [comment]
I've check it out this update on neutron module.
My deploy scenario is like this:
3 bare metal server: 1 allinone and 2 nodes.
I'm using KVM on ubuntu 12.04, each server with two NICs.
they are connected via public network with a external gateway(200.232.7.1) and another server running DNS and DHCP(200.232.7.10, via dnsmasq which I could easily disable). 

I've reset all my scenario and start again with the latest modifications on puppetlabs-havana, but I can't set up a network environment. When I assign one vm to my external network they get an IP address but they can't access Internet nor response for ping outside the netns. 

As I said this is probably happening cause I lack of knowledge on neutron. I'll review all my neutron/nova files to see what I'm missing, but thanks and appreciate your help!

**Comment by guimaluf** [comment]
As I said, my lack of skill on neutron lead me to read this basic guide and have a better working network on neutron.
http://docs.openstack.org/havana/install-guide/install/apt/content/install-neutron.configure-networks.html

**Comment by hogepodge** [comment]
The project has moved over to puppetlabs-openstack. With the latest puppet-neutron enhancements, I have code in place that tries to automatically set up your networking. Take a look at https://github.com/puppetlabs/puppetlabs-openstack/pull/11 and try out the new code over there.
