### ISSUE TITLE
Could not set 'file' on ensure: cannot generate tempfile `/etc/libvirt/qemu.conf on first run

### ISSUE THREAD

**Issue by benh57** [puppetlabs-toy-chest/puppetlabs-havana#5]
I know this is still in active development, but i figure i'd put this in anyway for tracking. ;)

The first time i apply on a new compute node, i always get this, because the /etc/libvirt dir is not there until the second run.

Error: Could not set 'file' on ensure: cannot generate tempfile `/etc/libvirt/qemu.conf20140122-7044-wlkt22-9' at 36:/etc/puppet/modules/havana/manifests/profile/nova/compute.pp
Error: Could not set 'file' on ensure: cannot generate tempfile`/etc/libvirt/qemu.conf20140122-7044-wlkt22-9' at 36:/etc/puppet/modules/havana/manifests/profile/nova/compute.pp
Wrapped exception:
cannot generate tempfile `/etc/libvirt/qemu.conf20140122-7044-wlkt22-9'
Error: /Stage[main]/Havana::Profile::Nova::Compute/File[/etc/libvirt/qemu.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: cannot generate tempfile`/etc/libvirt/qemu.conf20140122-7044-wlkt22-9' at 36:/etc/puppet/modules/havana/manifests/profile/nova/compute.pp

**Comment by beddari** [comment]
Thanks, we've also been getting this. I've been wondering wheter or not I should be contributing to this module and here you are - motivation might strike ;-)

It seems to be a dependency problem.

**Comment by hogepodge** [comment]
Probably a dependency problem. I think that libvirt and qemu are preinstalled on my test system, meaning the files exist before the run.
