### ISSUE TITLE
havana::controller::address::management issue

### ISSUE THREAD

**Issue by Adamooo** [puppetlabs-toy-chest/puppetlabs-havana#55]
Hi, I am trying to use puppet to deploy openstack havana, but I get this: 
Error 400 on SERVER: Could not find data item Havana::controller::address::management in any Hiera data file and no default supplied at /etc/puppet/modules/havana/manifests/resources/connectors.pp:3 on node controller

on the server I have hiera.yaml in /etc/puppet with common.yaml in /etc/puppet/hieradata
But it looks like it can't find them

[Private Network]
Management Network:172.16.33.0/24
Data Network 172.16.44.0/24

[External Network]
API Network & External Network is set in the same network which have access outside.

Rest were set almost the same as in this video: 
https://www.youtube.com/watch?v=hTrWcGHsHh4

Thanks for any hint

**Comment by guimaluf** [comment]
Hey adam, this module is out of use.
try to use https://github.com/puppetlabs/puppetlabs-openstack

**Comment by Adamooo** [comment]
Thanks 
I change module to puppetlabs-openstack

**Comment by a23121376** [comment]
Hi,I also meet the problem,how are your deal with?

**Comment by Adamoo** [comment]
I take newest version of it.
