### ISSUE TITLE
Check logic around upgrading iproute package to RDO version

### ISSUE THREAD

**Issue by beddari** [puppetlabs-toy-chest/puppetlabs-havana#6]
When using the earlier grizzly module for some demos we had an issue where iproute was not upgraded to the RDO version and had to do a manual upgrade of that before Neutron (then quantum) would work.

I haven't digged into the havana code yet but will watch for this when I do - hence this bug report. Don't know if anyone else has seen the same behaviour?

**Comment by benh57** [comment]
I'm not using RDO, but yes, i had to upgrade my iproute on centos 6.5 for Neutron to work with these packages (With namespaces on) It'd be nice if the puppet modules detected i had an incorrect iproute version and did that for me.

**Comment by hogepodge** [comment]
I'll look at adding a version requirement to make sure it's updated.

**Comment by beddari** [comment]
Really it could be considered a dependency issue with the RDO libvirt package, no? I haven't dug around the source of that package yet - but it possibly just depends on iproute in general.

**Comment by beddari** [comment]
I ended up writing an exec that does yum -y upgrade iproute unless rpm returns a package with the el6ost string in it. Not elegant but it works, I could PR that if it is acceptable.

**Comment by hogepodge** [comment]
I think that calling out yum explicitly isn't a great solution. Ensuring latest should be sufficient.

**Comment by hogepodge** [comment]
From a base installation of any RHEL system, you're going to need to do an offline (to puppet) update and reboot to get the networking to work. It's not ideal, but should change (along with a bunch of other stuff I don't necessarily want to think about) with RHEL 7.

**Comment by hogepodge** [comment]
closed by #35
